---
# tasks file for Sudoers_chanampa
- debug:
    msg: "iniciando tareas de sudoers_chanampa"

- name: "agregar al grupo GProfesores para que pueda ejecutar sudo sin clave"
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    line: '%GProfesores ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
