echo "ejecutando punto D"
echo "ansible"
echo "$(cd /home/mc/UTN-FRA_SO_Examenes/202408/ansible/ && ansible-playbook -i inventory/hosts playbook.yml --ask-become-pass)"
echo "------------------------------------------------------------"
echo "ARCHIVO DATOS.TXT"
echo "$(sudo cat /tmp/alumno/datos.txt)"
echo "------------------------------------------------------------"
echo "GRUPOS CREADOS"
echo "$(sudo cat /etc/group | tail -n2)"
echo "------------------------------------------------------------"
echo "USUARIOS CREADOS"
echo "$(sudo cat /etc/passwd | tail -n2)"
echo "------------------------------------------------------------"
echo "VERSIONES DE PROGRAMAS INSTALADOS"
echo "$(htop --version)"
echo "------------------------------"
echo "$(tmux --version)"
echo "------------------------------"
echo "$(tree --version)"
echo "------------------------------"
echo "$(speedtest-cli --version)"
echo "------------------------------"
echo "punto D terminado"
