echo "ejecutando punto B"
echo "$(cd /usr/local/bin/ && sudo ./chanampa_check_URL.sh /home/mc/UTN-FRA_SO_Examenes/202408/bash_script/Lista_URL.txt)"
echo "$(sudo tree /tmp/head-check)"
echo "ver archivo 200.log"
echo "$(sudo cat /var/log/200.log)"
echo "ver archivo 404.log"
echo "$(sudo cat /var/log/404.log)"
echo "ver archivo 500.log"
echo "$(sudo cat /var/log/500.log)"
echo "comando bash_script ejecutado"
